//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod activity_service;

// <<< CUSTOM
// END CUSTOM

pub use activity_service::ActivityService;
// <<< CUSTOM
// END CUSTOM
