-- Activity Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the activity.activities table.
-- Customize this file to add your initial data.

-- INSERT INTO activity.activities (
--     id,
--     company_id,
--     subject,
--     activity_type,
--     direction,
--     lead_id,
--     opportunity_id,
--     party_id,
--     status,
--     scheduled_at,
--     occurred_at,
--     assignee_id,
--     outcome,
--     notes,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO activity.activities (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

