-- Migration: Create activities table
-- Generated by metaphor-schema

-- Create activity_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activity_type') THEN
        CREATE TYPE activity_type AS ENUM ('whatsapp', 'call', 'email', 'meeting', 'visit', 'task', 'note', 'other');
    END IF;
END
$$;

-- Create activity_direction enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activity_direction') THEN
        CREATE TYPE activity_direction AS ENUM ('inbound', 'outbound');
    END IF;
END
$$;

-- Create activity_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activity_status') THEN
        CREATE TYPE activity_status AS ENUM ('planned', 'in_progress', 'done', 'cancelled');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS activity;

CREATE TABLE IF NOT EXISTS activity.activities (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    subject TEXT NOT NULL,
    activity_type activity_type NOT NULL DEFAULT 'whatsapp',
    direction activity_direction,
    lead_id UUID,
    opportunity_id UUID,
    party_id UUID,
    status activity_status NOT NULL DEFAULT 'planned',
    scheduled_at TIMESTAMPTZ,
    occurred_at TIMESTAMPTZ,
    assignee_id UUID,
    outcome TEXT,
    notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_activities_company_id_status ON activity.activities (company_id, status);

CREATE INDEX IF NOT EXISTS idx_activities_lead_id ON activity.activities (lead_id);

CREATE INDEX IF NOT EXISTS idx_activities_opportunity_id ON activity.activities (opportunity_id);

CREATE INDEX IF NOT EXISTS idx_activities_party_id ON activity.activities (party_id);

CREATE INDEX IF NOT EXISTS idx_activities_assignee_id_scheduled_at ON activity.activities (assignee_id, scheduled_at);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_activities_metadata_gin ON activity.activities USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_activities_metadata_deleted_at ON activity.activities ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_activities_metadata_created_at ON activity.activities ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_activities_metadata_updated_at ON activity.activities ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION activity.activities_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS activities_insert_audit ON activity.activities;
CREATE TRIGGER activities_insert_audit BEFORE INSERT ON activity.activities
    FOR EACH ROW EXECUTE FUNCTION activity.activities_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS activities_update_audit ON activity.activities;
CREATE TRIGGER activities_update_audit BEFORE UPDATE ON activity.activities
    FOR EACH ROW EXECUTE FUNCTION activity.activities_audit_timestamp();
