-- Audit Triggers Migration for activity module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Activity (activity.activities)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION activity.activities_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS activities_insert_audit ON activity.activities;
CREATE TRIGGER activities_insert_audit BEFORE INSERT ON activity.activities
    FOR EACH ROW EXECUTE FUNCTION activity.activities_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS activities_update_audit ON activity.activities;
CREATE TRIGGER activities_update_audit BEFORE UPDATE ON activity.activities
    FOR EACH ROW EXECUTE FUNCTION activity.activities_audit_timestamp();

