-- Company RLS fence for activity module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for activity.activities
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE activity.activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity.activities FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS activities_company_isolation ON activity.activities;
CREATE POLICY activities_company_isolation ON activity.activities
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

