-- Enum types for activity module
-- Generated by metaphor-schema

-- Create activity_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activity_type') THEN
        CREATE TYPE activity_type AS ENUM ('whatsapp', 'call', 'email', 'meeting', 'visit', 'task', 'note', 'other');
    END IF;
END
$$;

-- Create activity_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activity_status') THEN
        CREATE TYPE activity_status AS ENUM ('planned', 'in_progress', 'done', 'cancelled');
    END IF;
END
$$;

-- Create activity_direction enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activity_direction') THEN
        CREATE TYPE activity_direction AS ENUM ('inbound', 'outbound');
    END IF;
END
$$;

