//! Event handler trait for Activity events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ActivityEvent;

/// Event handler for Activity events.
/// Implement this trait to react to Activity lifecycle events.
pub trait ActivityEventHandler: EventHandler<ActivityEvent> {}
