//! Domain events for Activity entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Activity;

/// Domain events for Activity — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Activity>)` variant.
pub type ActivityEvent = CrudEvent<Activity>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Activity events.
pub type ActivityEventPublisher = Arc<dyn CrudEventPublisher<Activity> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopActivityEventPublisher = NoOpCrudEventPublisher<Activity>;
