//! Repository trait for Activity aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Activity aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Activity, ActivityDirection, ActivityStatus, ActivityType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ActivityPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ActivityPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ActivityPaginatedResult {
    pub data: Vec<Activity>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ActivityFilter {
    pub subject: Option<String>,
    pub activity_type: Option<ActivityType>,
    pub direction: Option<ActivityDirection>,
    pub lead_id: Option<Uuid>,
    pub opportunity_id: Option<Uuid>,
    pub party_id: Option<Uuid>,
    pub status: Option<ActivityStatus>,
    pub assignee_id: Option<Uuid>,
    pub outcome: Option<String>,
    pub notes: Option<String>,
}

impl ActivityFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.subject.is_some() || self.activity_type.is_some() || self.direction.is_some() || self.lead_id.is_some() || self.opportunity_id.is_some() || self.party_id.is_some() || self.status.is_some() || self.assignee_id.is_some() || self.outcome.is_some() || self.notes.is_some()
    }
}

/// Repository trait for Activity aggregate
///
/// This trait defines the persistence contract for Activity entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ActivityRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new activity entity
    async fn save(&self, entity: &Activity) -> Result<Activity>;

    /// Find activity by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Activity>>;

    /// Find all activity entities
    async fn find_all(&self) -> Result<Vec<Activity>>;

    /// Update activity by ID
    async fn update(&self, id: &str, entity: &Activity) -> Result<Option<Activity>>;

    /// Delete activity by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List activity with pagination
    async fn list(&self, params: ActivityPaginationParams) -> Result<ActivityPaginatedResult>;

    /// List activity with pagination and filters
    async fn list_with_filters(&self, params: ActivityPaginationParams, filters: ActivityFilter) -> Result<ActivityPaginatedResult>;

    /// Count all activity entities
    async fn count(&self) -> Result<u64>;

    /// Count activity entities matching filters
    async fn count_with_filters(&self, filters: ActivityFilter) -> Result<u64>;

    /// Check if activity exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete activity by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted activity by ID
    async fn restore(&self, id: &str) -> Result<Option<Activity>>;

    /// List soft-deleted activity entities
    async fn list_deleted(&self, params: ActivityPaginationParams) -> Result<ActivityPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save activity entities
    async fn bulk_save(&self, entities: &[Activity]) -> Result<Vec<Activity>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
