//! Repository for Activity entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Activity, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Activity;

/// Table name for Activity entities
pub const TABLE_NAME: &str = "activity.activities";

/// Repository for Activity entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ActivityRepository(
    backbone_orm::GenericCrudRepository<Activity, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ActivityRepository {
    type Target = backbone_orm::GenericCrudRepository<Activity, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ActivityRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ActivityRepository, Activity, soft_delete);
