//! Validator for Activity entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Activity>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Activity;

/// Validator type alias for Activity entities.
pub type ActivityValidator = EntityValidator<Activity>;

/// Build a validator for Activity with all schema-defined field rules.
pub fn activity_validator() -> ActivityValidator {
    EntityValidator::new()
        .rule(RequiredString::new("subject", |e: &Activity| &e.subject))
        .rule(OptionalNotBlank::new("outcome", |e: &Activity| e.outcome.as_deref()))
        .rule(OptionalNotBlank::new("notes", |e: &Activity| e.notes.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
