//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod activity_validator;

pub use activity_validator::{ActivityValidator, activity_validator};

// <<< CUSTOM
// END CUSTOM
