//! Activity API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Activity CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ACTIVITY TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Activity
pub struct ActivityTestData;

impl TestDataGenerator for ActivityTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "subject": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "activity_type": "whatsapp",
            "direction": null,
            "lead_id": null,
            "opportunity_id": null,
            "party_id": null,
            "status": "planned",
            "scheduled_at": now,
            "occurred_at": now,
            "assignee_id": null,
            "outcome": null,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "subject": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "activity_type": "whatsapp",
            "direction": null,
            "lead_id": null,
            "opportunity_id": null,
            "party_id": null,
            "status": "planned",
            "scheduled_at": now,
            "occurred_at": now,
            "assignee_id": null,
            "outcome": null,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ACTIVITY API TEST
// ============================================================================

/// Activity API test suite
pub struct ActivityApiTest {
    inner: GenericCrudTest<ActivityTestData>,
}

impl ActivityApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/activities", "Activity");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ActivityTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ActivityApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_activity_crud() {
        let mut test = ActivityApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Activity specific tests here
// <<< CUSTOM TESTS END >>>
