//! Activity Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Activity exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use activity::exports::{ActivityDto, ActivityQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `ActivityDto` - Data transfer object for Activity
/// - `ActivitySummary` - Summary view of Activity
/// - `ActivityId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `ActivityQueryService` - Read-only queries
///
/// ## Public Events
/// - `ActivityCreatedEvent` - Published when Activity is created
/// - `ActivityUpdatedEvent` - Published when Activity is updated
/// - `ActivityDeletedEvent` - Published when Activity is deleted
pub struct ExportSummary;
