//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod activity_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use activity_handler::{create_activity_routes, create_activity_read_routes, create_activity_write_routes};
// <<< CUSTOM
// END CUSTOM
